steps:
  # Step 1: Build the Docker image (--no-cache forces fresh build)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/grove-foundation'
      - '--build-arg'
      - 'GEMINI_API_KEY=$_GEMINI_API_KEY'
      - '.'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/grove-foundation']

  # Step 3: Deploy to Cloud Run with secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'grove-foundation'
      - '--image'
      - 'gcr.io/$PROJECT_ID/grove-foundation'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--update-secrets'
      - 'GEMINI_API_KEY=GEMINI_API_KEY:latest,SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest'
      - '--set-env-vars'
      - 'GCS_BUCKET_NAME=grove-assets'

  # Step 4: Wait for deployment to stabilize and verify health
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting for deployment to stabilize..."
        sleep 30

        SERVICE_URL=$$(gcloud run services describe grove-foundation \
          --platform=managed \
          --region=us-central1 \
          --format='value(status.url)')

        echo "Service URL: $$SERVICE_URL"

        # Health check with retry
        for i in 1 2 3 4 5; do
          echo "Health check attempt $$i..."
          RESPONSE=$$(curl -s -o /dev/null -w "%{http_code}" "$$SERVICE_URL/api/health/ready")
          if [ "$$RESPONSE" = "200" ]; then
            echo "✓ Health check passed"
            exit 0
          fi
          echo "Health check returned $$RESPONSE, retrying in 10s..."
          sleep 10
        done

        echo "✗ Health check failed after 5 attempts"
        gcloud logging read "resource.type=cloud_run_revision AND resource.labels.service_name=grove-foundation" \
          --limit=20 --format="table(timestamp,textPayload)"
        exit 1

images:
  - 'gcr.io/$PROJECT_ID/grove-foundation'

substitutions:
  _GEMINI_API_KEY: ''  # Passed from trigger or command line

options:
  logging: CLOUD_LOGGING_ONLY
