steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/gen-lang-client-0939607979/grove-foundation', '--build-arg', 'GEMINI_API_KEY=$_GEMINI_API_KEY', '.' ]
images:
- 'gcr.io/gen-lang-client-0939607979/grove-foundation'
