// types/lens.ts — Complete Data Model for Custom Lens System
// This file extends the existing narratives-schema types with custom lens support

import { PersonaColor, NarrativeStyle, ArcEmphasis, OpeningPhase, Persona } from '../data/narratives-schema';

// ============================================================
// CORE TYPES
// ============================================================

export type ArchetypeId =
  | 'academic'
  | 'engineer'
  | 'concerned-citizen'
  | 'geopolitical'
  | 'big-ai-exec'
  | 'family-office';

// Re-export from narratives-schema for convenience
export type { PersonaColor, NarrativeStyle, ArcEmphasis, OpeningPhase };

export type NarrativePhase = 'hook' | 'stakes' | 'mechanics' | 'evidence' | 'resolution';

// ============================================================
// CUSTOM LENS TYPES
// ============================================================

/**
 * Base interface for both archetypal and custom personas
 * Extends the existing Persona type with additional custom lens fields
 */
export interface BasePersona {
  id: string;
  publicLabel: string;
  description: string;
  icon: string;
  color: PersonaColor | 'purple';  // purple added for custom lenses
  enabled: boolean;

  // Narrative configuration
  toneGuidance: string;
  narrativeStyle: NarrativeStyle;
  arcEmphasis: ArcEmphasis;
  openingPhase: OpeningPhase;
  defaultThreadLength: number;

  // Journey configuration
  entryPoints: string[];
  suggestedThread: string[];
}

/**
 * Archetypal persona (built-in lens with conversion path)
 */
export interface ArchetypalPersona extends BasePersona {
  isCustom: false;
  conversionPath: ConversionPath;
}

/**
 * Custom lens created by user through wizard
 */
export interface CustomLens extends BasePersona {
  isCustom: true;
  userInputs: EncryptedUserInputs;      // Encrypted original responses
  archetypeMapping: ArchetypeId;         // Hidden mapping for conversion routing
  createdAt: string;                     // ISO timestamp
  lastUsedAt?: string;                   // Track engagement
  journeysCompleted: number;             // Track depth
}

export type PersonaOrLens = ArchetypalPersona | CustomLens;

// ============================================================
// USER INPUT TYPES (for wizard)
// ============================================================

export interface UserInputs {
  // Question 1: What brings them here
  motivation: MotivationType;
  motivationOther?: string;

  // Question 2: What concerns them (conditional on motivation)
  concerns?: ConcernType;
  concernsOther?: string;

  // Question 3: Future outlook
  futureOutlook: FutureOutlookType;
  futureOutlookOther?: string;

  // Question 4: Professional relationship
  professionalRelationship: ProfessionalRelationshipType;
  professionalRelationshipOther?: string;

  // Question 5: Free-form worldview (optional, enriches generation)
  worldviewStatement?: string;
}

export type MotivationType =
  | 'worried-about-ai'
  | 'researching-distributed-systems'
  | 'someone-sent-link'
  | 'investment-opportunities'
  | 'just-curious'
  | 'other';

export type ConcernType =
  | 'big-tech-power'
  | 'job-displacement'
  | 'energy-environment'
  | 'privacy'
  | 'harder-to-articulate'
  | 'other';

export type FutureOutlookType =
  | 'cautiously-optimistic'
  | 'genuinely-worried'
  | 'depends-on-control'
  | 'building-conflicted'
  | 'other';

export type ProfessionalRelationshipType =
  | 'build-it'
  | 'fund-invest'
  | 'study-regulate'
  | 'use-dont-trust'
  | 'lead-orgs'
  | 'other';

// ============================================================
// ENCRYPTED DATA TYPES
// ============================================================

export interface EncryptedUserInputs {
  iv: number[];    // Initialization vector for AES-GCM
  data: number[];  // Encrypted ciphertext
}

// ============================================================
// LENS GENERATION TYPES
// ============================================================

/**
 * Candidate lens generated by AI
 */
export interface LensCandidate {
  publicLabel: string;
  description: string;
  toneGuidance: string;
  narrativeStyle: NarrativeStyle;
  arcEmphasis: ArcEmphasis;
  openingPhase: OpeningPhase;
  archetypeMapping: ArchetypeId;
}

export interface GenerateLensRequest {
  userInputs: UserInputs;
}

export interface GenerateLensResponse {
  lensOptions: LensCandidate[];
}

// ============================================================
// CONVERSION PATH TYPES
// ============================================================

export interface ConversionCTA {
  id: string;
  label: string;
  description: string;
  action: CTAAction;
  priority: 'primary' | 'secondary' | 'tertiary';
}

export type CTAAction =
  | { type: 'modal'; modalId: string }
  | { type: 'link'; url: string; external?: boolean }
  | { type: 'email'; template: string }
  | { type: 'calendly'; url: string }
  | { type: 'form'; formId: string };

export interface ConversionPath {
  archetypeId: ArchetypeId;
  headline: string;           // "You've seen what distributed AI could mean for [X]"
  subheadline: string;        // Archetype-specific framing
  ctas: ConversionCTA[];
}

// ============================================================
// REVEAL STATE TYPES
// ============================================================

export interface RevealState {
  simulationRevealShown: boolean;
  simulationRevealAcknowledged: boolean;
  customLensOfferShown: boolean;
  terminatorModeUnlocked: boolean;
  terminatorModeActive: boolean;
  founderStoryShown: boolean;
  ctaViewed: boolean;
}

export const DEFAULT_REVEAL_STATE: RevealState = {
  simulationRevealShown: false,
  simulationRevealAcknowledged: false,
  customLensOfferShown: false,
  terminatorModeUnlocked: false,
  terminatorModeActive: false,
  founderStoryShown: false,
  ctaViewed: false
};

// ============================================================
// EXTENDED SESSION TYPES
// ============================================================

/**
 * Extended terminal session with reveal tracking and custom lens support
 * This extends the base TerminalSession from narratives-schema.ts
 */
export interface ExtendedTerminalSession {
  sessionId: string;
  activeLens: string | null;      // Persona ID or custom lens ID
  isCustomLens: boolean;          // Quick check for custom vs archetypal
  scholarMode: boolean;

  // Journey tracking
  currentThread: string[];
  currentPosition: number;
  visitedCards: string[];
  journeysCompleted: number;
  topicsExplored: number;
  exchangeCount: number;

  // Time tracking
  startedAt: string;              // ISO timestamp
  lastActivityAt: string;         // ISO timestamp
  minutesActive: number;          // Calculated from timestamps

  // Reveal tracking
  revealState: RevealState;
}

export const DEFAULT_EXTENDED_SESSION: ExtendedTerminalSession = {
  sessionId: '',
  activeLens: null,
  isCustomLens: false,
  scholarMode: false,
  currentThread: [],
  currentPosition: 0,
  visitedCards: [],
  journeysCompleted: 0,
  topicsExplored: 0,
  exchangeCount: 0,
  startedAt: '',
  lastActivityAt: '',
  minutesActive: 0,
  revealState: DEFAULT_REVEAL_STATE
};

// ============================================================
// WIZARD STATE TYPES
// ============================================================

export type WizardStep =
  | 'privacy'
  | 'input-motivation'
  | 'input-concerns'
  | 'input-outlook'
  | 'input-professional'
  | 'input-worldview'
  | 'generating'
  | 'select'
  | 'confirm';

export interface WizardState {
  currentStep: WizardStep;
  userInputs: Partial<UserInputs>;
  generatedOptions: LensCandidate[];
  selectedOption: LensCandidate | null;
  isGenerating: boolean;
  error: string | null;
}

export const DEFAULT_WIZARD_STATE: WizardState = {
  currentStep: 'privacy',
  userInputs: {},
  generatedOptions: [],
  selectedOption: null,
  isGenerating: false,
  error: null
};

// ============================================================
// ANALYTICS TYPES
// ============================================================

export type FunnelEventType =
  | 'session_started'
  | 'lens_picker_viewed'
  | 'archetypal_lens_selected'
  | 'journey_started'
  | 'card_viewed'
  | 'journey_completed'
  | 'simulation_reveal_reached'
  | 'simulation_reveal_clicked'
  | 'custom_lens_wizard_started'
  | 'custom_lens_step_completed'
  | 'custom_lens_created'
  | 'terminator_mode_activated'
  | 'founder_story_viewed'
  | 'cta_viewed'
  | 'cta_clicked'
  | 'invitation_sent'
  | 'lens_shared';

export interface FunnelEvent {
  eventType: FunnelEventType;
  sessionId: string;
  timestamp: string;

  // Optional context
  archetypeId?: ArchetypeId;
  customLensId?: string;
  cardId?: string;
  journeyIndex?: number;
  ctaId?: string;
  stepNumber?: number;
  metadata?: Record<string, unknown>;
}

// ============================================================
// STORAGE TYPES
// ============================================================

export interface StoredCustomLenses {
  version: '1.0';
  lenses: CustomLens[];
  lastUpdated: string;
}

export interface StoredSession {
  version: '1.0';
  session: ExtendedTerminalSession;
}

// ============================================================
// TYPE GUARDS
// ============================================================

export function isCustomLens(persona: PersonaOrLens | Persona | null): persona is CustomLens {
  if (!persona) return false;
  return 'isCustom' in persona && persona.isCustom === true;
}

export function isArchetypalPersona(persona: PersonaOrLens | Persona | null): persona is ArchetypalPersona {
  if (!persona) return false;
  return 'isCustom' in persona && persona.isCustom === false;
}

export function hasConversionPath(persona: unknown): persona is { conversionPath: ConversionPath } {
  return typeof persona === 'object' &&
         persona !== null &&
         'conversionPath' in persona;
}

// ============================================================
// ARCHETYPE MAPPING HELPERS
// ============================================================

/**
 * Map existing persona IDs to archetype IDs for conversion routing
 */
export const PERSONA_TO_ARCHETYPE: Record<string, ArchetypeId> = {
  'concerned-citizen': 'concerned-citizen',
  'academic': 'academic',
  'engineer': 'engineer',
  'geopolitical': 'geopolitical',
  'big-ai-exec': 'big-ai-exec',
  'family-office': 'family-office'
};

/**
 * Get archetype for any persona (custom or archetypal)
 */
export function getArchetypeForPersona(persona: PersonaOrLens | Persona | null): ArchetypeId | null {
  if (!persona) return null;

  if (isCustomLens(persona)) {
    return persona.archetypeMapping;
  }

  return PERSONA_TO_ARCHETYPE[persona.id] || null;
}
